const path = require('path')
module.exports = {
    dir: path.join(__dirname, './static/font'),
    list: [
        {path: 'msyh.ttf', family: 'MicrosoftYaHei'},
        {path: 'msyhbd.ttf', family: 'MicrosoftYaHei-Bold'},
        {path: '方正粗圆简体.ttf', family: 'FZY4JW--GBK1-0'},
        {path: '腾讯体-W7.otf', family: 'TTTGBMedium'},
        {path: '方正正黑简体.ttf', family: 'FZZHJW--GB1-0'},
        {path: '方正粗圆简体.ttf', family: 'FZY4JW--GBK1-0'},
        {path: '方正正纤黑简体.ttf', family: 'FZZXHJW--GB1-0'},
        {path: '方正正中黑简体.ttf', family: 'FZZZHONGJW--GB1-0' },
        {path: '方正兰亭黑简体.ttf', family: 'FZLTHK--GBK1-0' },
        {path: '方正兰亭中黑简体.ttf', family: 'FZLTZHK--GBK1-0' },
        {path: '方正兰亭大黑简体.ttf', family: 'FZDHTJW--GB1-0' },
        {path: '方正尚酷简体.ttf', family: 'FZSKJW--GB1-0' },
        {path: '方正粗宋简体.ttf', family: 'FZCSJW--GBK1-0' },
        {path: '方正粗圆简体.ttf', family: 'FZY4JW--GBK1-0' },
        {path: '方正舒体简体.ttf', family: 'FZSTK--GBK1-0' },
        {path: '方正汉真广标简体.ttf', family: 'FZHZGBJW--GBK1-0' },
        {path: '汉仪菱心体简.ttf', family: 'HYk2gj' },
        {path: '汉仪综艺体简.ttf', family: 'HYk1gj' },
        {path: '汉仪大宋简.ttf', family: 'HYa4gj' },
        {path: 'SourceHanSansCN-ExtraLight.otf', family: 'SourceHanSansCN-ExtraLight' },
        {path: 'SourceHanSansCN-Light.otf', family: 'SourceHanSansCN-Light' },
        {path: 'SourceHanSansCN-Normal.otf', family: 'SourceHanSansCN-Normal' },
        {path: 'SourceHanSansCN-Regular.otf', family: 'SourceHanSansCN-Regular' },
        {path: 'SourceHanSansCN-Medium.otf', family: 'SourceHanSansCN-Medium' },
        {path: 'SourceHanSansCN-Bold.otf', family: 'SourceHanSansCN-Bold' },
        {path: 'SourceHanSansCN-Heavy.otf', family: 'SourceHanSansCN-Heavy' },
        {path: 'PingFang-SC-Regular.ttf', family: 'PingFang-SC-Regular' },
    ]
}